---
- name: Install novnc and tigervnc-server
  hosts: localhost
  become: yes
  gather_facts: yes
  connection: local
  collections: # ansible-galaxy collection install community.crypto ansible.posix community.general
    - community.crypto.x509_certificate
    - ansible.posix
    - community.general

  vars:
    NOVNC_SYSTEMD_SERVICE: ./files/novnc.service
    VNCCONFIG: ./files/vncconfig
    VNC_USERNAME: lab-user
    NOVNC_PASSWORD: redhat
    USERNAME_GROUP: users
    NOVNC_IP_ADDRESS_FILE: /home/{{ VNC_USERNAME }}/external_ip
    
  tasks:

  - name: Make sure the VNC_USERNAME user exists
    ansible.builtin.user:
      name: "{{ VNC_USERNAME }}"
      groups: wheel
      append: yes

  - name: Ensure VNC_USERNAME has NOPASSWD sudo
    ansible.builtin.lineinfile:
      path: "/etc/sudoers.d/{{ VNC_USERNAME }}"
      line: "{{ VNC_USERNAME }} ALL=(ALL)       NOPASSWD: ALL"
      create: yes
      owner: root
      group: root

  - name: Install epel
    ansible.builtin.yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      state: present
      disable_gpg_check: true

  - name: Install novnc and tigervnc-server
    ansible.builtin.yum:
      name: "{{ novnc_packages }}"
    vars:
      novnc_packages:
      - novnc
      - python-websockify
      - numpy
      - "@Server with GUI"
      - tigervnc-server

  - name: Create a private key for the certificate signing request
    community.crypto.openssl_privatekey:
      path: /root/self.key

  - name: Generate a certificate signing request
    community.crypto.openssl_csr:
      path: /root/self.csr
      privatekey_path: /root/self.key
      common_name: "{{ ansible_hostname }}"
      email_address: "{{ VNC_USERNAME }}@{{ ansible_domain }}"
      country_name: "US"
      state_or_province_name: "North Carolina"
      locality_name: "Raleigh"
      organization_name: "Red Hat"
      organizational_unit_name: "Workshop"

  - name: Generate a cert in /root
    openssl_certificate:
      path: /root/self.crt
      privatekey_path: /root/self.key
      csr_path: /root/self.csr
      provider: selfsigned

  - name: Create novnc systemd service
    ansible.builtin.copy:
      src: "{{ NOVNC_SYSTEMD_SERVICE }}"
      dest: /usr/lib/systemd/system/novnc.service
      owner: root
      group: root
      mode: 0644
      seuser: system_u
      serole: object_r
      setype: vmtools_unit_file_t
      selevel: s0

  - name: Start and enable novnc.service
    ansible.builtin.systemd:
      daemon_reload: true
      state: started
      enabled: true
      name: novnc

  - name: Create tigervnc systemd service
    ansible.builtin.command: cp /usr/lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@:1.service

  - name: Add {{ VNC_USERNAME }} to vncusers
    ansible.builtin.lineinfile:
      path: /etc/tigervnc/vncserver.users
      line: ":1={{ VNC_USERNAME }}"
      create: yes

  - name: Make {{ VNC_USERNAME }}/.vnc
    ansible.builtin.file:
      path: "/home/{{ VNC_USERNAME }}/.vnc"
      state: directory
    become_user: "{{ VNC_USERNAME }}"

  - name: Set vnc password
    become_user: "{{ VNC_USERNAME }}"
    ansible.builtin.shell: printf "{{ NOVNC_PASSWORD }}\n{{ NOVNC_PASSWORD }}\n\n" | vncpasswd

  - name: Create .vnc/config
    ansible.builtin.copy:
      src: "{{ VNCCONFIG }}"
      dest: "/home/{{ VNC_USERNAME }}/.vnc/config"
      owner: "{{ VNC_USERNAME }}"
      group: "{{ USERNAME_GROUP }}"
      mode: 0644

  - name: Set gnome session for vnc
    ansible.builtin.lineinfile:
      path: "/home/{{ VNC_USERNAME }}/.session"
      line: "gnome-session"
      create: yes
      owner: "{{ VNC_USERNAME }}"
      group: "{{ USERNAME_GROUP }}"

  - name: Create firewall rules for novnc
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    with_items:
      - https
      - vnc-server

  - name: Start and enable vnc.service
    ansible.builtin.systemd:
      state: started
      enabled: true
      name: vncserver@:1.service

  - name: Get NOVNC_IP_ADDRESS_FILE
    ansible.builtin.command: cat {{ NOVNC_IP_ADDRESS_FILE }}
    register: NOVNC_IP_ADDRESS
    # Referenced as NOVNC_IP_ADDRESS_PASSWORD.stdout

  - name: Write novnc URL to a file
    copy: 
      dest: "/home/{{ VNC_USERNAME }}/novnc_url.html"
      content: |
        Your desktop interface can be reached at https://{{ NOVNC_IP_ADDRESS.stdout }}/vnc.html?host={{ NOVNC_IP_ADDRESS.stdout }}&port=443
    delegate_to: localhost
